---
# Global variables for all hosts
ansible_python_interpreter: /usr/bin/python3

# Security settings
security_timezone: UTC
security_ntp_servers:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org

# Logging settings
log_retention_days: 30
log_rotation_size: 100M
