---
- name: Test Connection to Server
  hosts: test-servers
  gather_facts: yes

  tasks:
    - name: Display connection information
      debug:
        msg:
          - "=== Connection Test ==="
          - "Host: {{ inventory_hostname }}"
          - "IP: {{ ansible_host }}"
          - "User: {{ ansible_user }}"
          - "Python: {{ ansible_python_interpreter }}"
          - "Distribution: {{ ansible_distribution }} {{ ansible_distribution_version }}"
          - "Architecture: {{ ansible_architecture }}"
          - "Memory: {{ ansible_memtotal_mb }}MB"
          - "CPU Cores: {{ ansible_processor_cores }}"

    - name: Check if required packages are available
      package_facts:
        manager: auto

    - name: Display package manager
      debug:
        msg: "Package manager: {{ ansible_pkg_mgr }}"

    - name: Test GitHub API connectivity
      uri:
        url: https://api.github.com
        method: GET
        status_code: 200
      register: github_api_test

    - name: Display GitHub API test result
      debug:
        msg: "GitHub API connectivity: {{ 'SUCCESS' if github_api_test.status == 200 else 'FAILED' }}"

    - name: Check systemd availability
      stat:
        path: /etc/systemd/system
      register: systemd_check

    - name: Display systemd check
      debug:
        msg: "Systemd available: {{ systemd_check.stat.exists }}"
